config/routes.rb
Rails.application.routes.draw do
  get 'inquiries/index'=> 'inquiries#index'
  post 'inquiries/confirm', to: 'inquiries#confirm'
  post 'inquiries/complete', to: 'inquiries#complete'

  get "papers/login" => "papers#login_form"
  post "papers/login" => "papers#login"
  post "papers/logout" => "papers#logout"
  post "papers/:id/update" => "papers#update"
  get "papers/:id/edit" => "papers#edit"
  post "papers/create" => "papers#create"
  get "papers/signup" => "papers#new"
  get "papers/index" => "papers#index"
  get "papers/:id" => "papers#show"

  get "blogs/index" => "blogs#index"
  get "blogs/new" => "blogs#new"
  get "blogs/:id" => "blogs#show"
  post "blogs/create" => "blogs#create"
  get "blogs/:id/edit" => "blogs#edit"
  post "blogs/:id/update" => "blogs#update"
  post "blogs/:id/destroy" => "blogs#destroy"

  get "users/login" => "users#login_form"
  post "users/login" => "users#login"
  post "users/logout" => "users#logout"
  post "users/:id/update" => "users#update"
  get "users/:id/edit" => "users#edit"
  post "users/create" => "users#create"
  get "users/signup" => "users#new"
  get "users/index" => "users#index"
  get "users/:id" => "users#show"

  get "posts/index" => "posts#index"
  get "posts/new" => "posts#new"
  get "posts/:id" => "posts#show"
  post "posts/create" => "posts#create"
  get "posts/:id/edit" => "posts#edit"
  post "posts/:id/update" => "posts#update"
  post "posts/:id/destroy" => "posts#destroy"

  get "/top" => "home#top"
  get "home/service" => "home#service"
  get "home/message" => "home#message"
end

app/models/inquiry.rb
class Inquiry
  include ActiveModel::Model

  attr_accessor :name, :email, :message

  validates :name, :presence => {:message => '名前を入力してください'}
  validates :email, :presence => {:message => 'メールアドレスを入力してください'}
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
  def index
    @inquiry = Inquiry.new
    render :action => 'index'
  end

  def confirm
    # 入力値のチェック
    @inquiry = Inquiry.new(inquiry_params)
    if @inquiry.valid?
      # OK。確認画面を表示
      render :action => 'confirm'
    else
      # NG。入力画面を再表示
      render :action => 'index'
    end
  end

  def complete
    # メール送信
    @inquiry = Inquiry.new(inquiry_params)
    InquiryMailer.inquiry_email(@inquiry).deliver_now

    # 完了画面を表示
    render :action => 'complete'
  end

  private

  def inquiry_params
    params.require(:inquiry).permit(:name, :email, :message)
  end
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/views/inquiries/complete.html.erb
<head>
      <meta name="viewport" content="width=device-width,initial-scale=1">
      <!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-129331504-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-129331504-1');
</script>

</head>

<div class="top-wrapper">
<div class="page-header">
  <h1>お問い合わせ</h1>
</div>
<p>
  お問い合わせが完了しました。
</p>
</div>

app/views/inquiries/confirm.html.erb
<head>
      <meta name="viewport" content="width=device-width,initial-scale=1">
      <!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-129331504-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-129331504-1');
</script>

</head>

<div class="page-header">
  <h1>お問い合わせ</h1>
</div>

<%= form_for @inquiry, :url => inquiries_complete_path do |f| %>
  <table class="table">
    <tr>
      <th>名前</th>
      <td>
        <%= f.hidden_field :name %>
        <%= @inquiry.name %>
      </td>
    </tr>
    <tr>
      <th>メールアドレス</th>
      <td>
        <%= f.hidden_field :email %>
        <%= @inquiry.email %>
      </td>
    </tr>
    <tr>
      <th>お問い合わせ内容</th>
      <td>
        <%= f.hidden_field :message %>
        <%= simple_format(@inquiry.message) %>
      </td>
    </tr>
  </table>
  <%= f.submit '送信', :class => 'btn btn-primary' %>
<% end %>

app/views/inquiries/index.html.erb
<head>
      <meta name="viewport" content="width=device-width,initial-scale=1">
      <!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-129331504-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-129331504-1');
</script>

</head>

<div class="top-wrapper">
<%= form_for @inquiry, :url => inquiries_confirm_path do |f| %>
  <div class="page-header">
    <h1>お問い合わせ</h1>
  </div>

  <% if @inquiry.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <strong>入力内容にエラーがあります</strong>
      <ul>
        <% @inquiry.errors.each do |attr, msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <table class="table">
    <tr>
      <th>名前<span class="text-danger">（必須）</span></th>
      <td><%= f.text_field :name %></td>
    </tr>
    <tr>
      <th>メールアドレス<span class="text-danger">（必須）</span></th>
      <td><%= f.text_field :email %></td>
    </tr>
    <tr>
      <th>お問い合わせ内容</th>
      <td><%= f.text_area :message %></td>
    </tr>
  </table>
  <%= f.submit '確認', class: 'btn btn-primary' %>
<% end %>
</div>